name: deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 21

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Build Project
        uses: actions/upload-artifact@v2
        with:
          name: prod-files
          path: ./dist

      - name: Deploy app
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  # deploy:
  #   name: Deploy
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: prod-files
  #         path: ./dist

  #     - name: Deploy app
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./dist



